name: ci-tests

on: pull_request

jobs:
  pre-commit:
    name: Check pre-commit integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: python -m pip install pre-commit

    - name: Install pre-commit
      run: |
        pre-commit install

    - name: Update pre-commit
      run: |
        pre-commit autoupdate

    - name: Run pre-commit
      run: |
        pre-commit run -a

  check:
    name: Check Changelog Fragments
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 

    - name: Ensure base branch exists
      run: git fetch origin ${{ github.base_ref }}

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: python -m pip install towncrier

    - name: Check new fragment exists
      run: towncrier check --compare-with "origin/${{ github.base_ref }}"
